### ISSUE TITLE
Stream Internet radio

### ISSUE THREAD

**Issue by cknost** [morrolinux/mpradio#16]
I wish a feature to stream Internet radio.

**Comment by morrolinux** [comment]
Dear @preterive, I thought about your request and went to the conclusion that this feature is no-use for this project because:
- you would need a remote (android app?/desktop utility) to chose which station to play 
- you would need a way to switch between webradio and Bluetooth/mp3 
for both reasons, you would need to use your phone/pc anyways, and it's much more simple and efficient to just use your phone/pc to listen to Internet radio and stream via bluetooth to the Pi, just like you would to for youtube videos or so.
I've upgraded the project and added many interesting features, take a look if you'd like
