### ISSUE TITLE
Building system

### ISSUE THREAD

**Issue by vbextreme** [morrolinux/mpradio#21]
You need a build system and remove your orrible script.
Try https://www.gnu.org/software/make/
Or modern  http://mesonbuild.com with https://ninja-build.org

**Comment by morrolinux** [comment]
Don't worry I'm already making use of make for C++ parts, as you might have seen.
You seem more interested in pissing me off rather than contributing and that's not what this place for, so please GTFO of here with #20 and #21 since none of these are even issues by the way.
I use C++ for a better queue management and I don't really see a problem with it if i have a few non-frequent system calls to get the process pipe started. Things are still evolving by the way, so few things are still "raw" as we are in an "alpha" stage. 
Regards
