### ISSUE TITLE
"Losing signal" between songs

### ISSUE THREAD

**Issue by fryslanboppe** [morrolinux/mpradio#53]
Between the songs, theres 1 or 2 seconds of very loud noise. The same noise as when there's no signal (as when the Pi is turned off.)

**Comment by morrolinux** [comment]
Yeah, that's the supposed behaviour. 
Since each song is being played as a separate process/pipe, it's normal for it to skip between the end of the pipe and the new process being launched. 
The alternative would be to use a named pipe (to be kept always active)
But this way you could easily get the last "half a second" of the last played song to be looped until a new song starts (which is not really pleasant to hear either) because of buffer.
So a possible solution could be to generate/play 1 second of silence after each song... 
developers are welcome btw :)
